name: libchess-ci
on:
    push:
        branches: [ '**' ]

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v3
            - name: Install Nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: Install Dependencies
              run: npm ci
            - name: Run Tests
              run: npm run test -- --forceExit

    lint:
        name: Run linter
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v3
            - name: Install Nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: Install Dependencies
              run: npm ci
            - name: Run eslint
              run: npx eslint index.js src 

    check-version:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v3
            - name: Install Nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: Check Version Increment
              run: scripts/check_version.sh

    push-to-registry:
        needs: [test, lint, check-version]
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Get version number
              run: echo "VERSION=$(./get_version.sh)" >> $GITHUB_ENV

            - name: Log in to registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ secrets.GHCR_USERNAME }}
                password: ${{ secrets.GHCR_TOKEN }}

            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ghcr.io/${{ github.repository }}:${{ env.VERSION }}

